apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rails-ingress
spec:
  rules:
  - http:
      paths:
      - path: /rails
        backend:
          serviceName: rails-frontend
          servicePort: 3000
